spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lagou_work_3_4?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
lagouwork:
  limit:
    time-lenth: 2 
    visit-times: 30
